// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EnumTest.Models
{
    public partial class employeeSelectAllResult
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string city { get; set; }
    }
}
